name = "valorwave-admin-worker"
main = "_worker.js"
compatibility_date = "2024-12-01"

[vars]
GITHUB_CLIENT_ID ="Ov23lihmfzwhx2UQraRM"
WORKER_DOMAIN = "valorwave-admin-worker.sammassengale82.workers.dev"
CALLBACK_URL = "https://valorwave-admin-worker.sammassengale82.workers.dev/oauth/callback