name = "valorwave-admin-worker"
main = "_worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# This tells Wrangler to bundle your entire repo as static assets
[assets]
directory = "."
binding = "ASSETS"

[vars]
GITHUB_OWNER = "sammassengale82"
GITHUB_REPO = "Valorwave-Admin"
GITHUB_BRANCH = "main"

GITHUB_CLIENT_ID = "Ov23lihmfzwhx2UQraRM"
WORKER_DOMAIN = "valorwave-admin-worker.sammassengale82.workers.dev"
CALLBACK_URL = "https://valorwave-admin-worker.sammassengale82.workers.dev/oauth/callback"